# Generated by Django 4.2 on 2025-10-27 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0002_alter_loanapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='account',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='application',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='documents',
            field=models.ManyToManyField(to='loan.loandocument'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='type',
            field=models.CharField(choices=[('home_lone', 'Home Lone'), ('car_lone', 'Car Lone'), ('sme_lone', 'SME Lone'), ('personal_lone', 'Personal Lone')], default='Home Loan', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrers', to=settings.AUTH_USER_MODEL),
        ),
    ]
